### ISSUE TITLE
Dots/Particles instead of Snakes due to time constraint?

### ISSUE THREAD

**Issue by jeremytsang1** [osu-eastbay-study-group/circle-game-game-off-2019#4]
So I'm probably not going to have time to get an entire snake working by Saturday but I do think I can make a decent amount of progress if we just get the game working using colored dots. We can use the following colors
-  blue: the player
-  green: the items/loot/goals (or whatever you'd like to name it) the player needs to collect to score points
-  red: for enemy particles that can kill the player
![circle-game-initial-state](https://user-images.githubusercontent.com/20622143/69817536-aa293e00-11af-11ea-87b0-68a4de80ec7b.png)

For each color of dot, they will all be located on one  of `n` circles with radii` r_0, r_1, ..., r_{n-1}`. We can store these radii in a list and the player's (blue) dot can jump by incrementing or decrementing some index counter for said list. The red dots can all move in the same direction (all clockwise or all counterclockwise) to keep things simple, and just have the player keep collecting the green dots while spawning new red and green dots each time the player collects a green dot.

Now this part may be violating KISS, but I was thinking we can try to model each as an object of a different class derived from a base `PolarPlaceable` class. I didn't have time to make a proper UML diagram but just a crude sketch of some examples of classes I thought we might need in the below section.

# Classes
### `draw()`
- passes relevant data to PyGame to draw the object in the appropriate
  place in the window.
- probably pass data to the a coordinate converter on the Pygame side
  so this way we don't have to worry about to sets of coordinates when
  dealing with the dots.
## `class Loot(PolarPlaceable)`
- the "green dot"
#### `number of points`
- assigned at initialization
- make inversely proportionate to `radius_index` if time permets
#### `theta_step`
- how much to increase or decrease the angle
#### `increase_theta`
- used to move counterclockwise
  - (just like the unit circle from trigonometry moves counter
    clockwise with increasing angles)
#### `decrease_theta`
- used to move clockwise
## `class Enemy(Orbiter)`
- the "red dot"
## `class Player(Orbiter)`
- the "blue dot"

**Comment by positive235** [comment]
changed the color of player: blue dot-> hotpink dot

**Comment by jeremytsang1** [comment]
Got everything that I wanted to work!
